image:
  file: .gitpod.Dockerfile

# init tasks are ran in prebuilds, command tasks are run when the user starts a new session.
tasks:
  - name: Install Packages (Global)
    init: yarn
    # Since we cannot call this command during the workspace creation process, we'll call sync-done after the workspace is ready.
    command: gp sync-done yarn-install

  - name: Setup Web/Api Server
    command: |
      gp sync-await yarn-install 
      yarn setup
      yarn dev

vscode:
  extensions:
    # Prettier VS Code extension
    - esbenp.prettier-vscode
    # VS Code intgration for ShellCheck so see the docs on how to ignore errors, among other things
    - timonwong.shellcheck
    # VS Code icon theme Fireship.io uses (Disclaimer: @ajhalili2006 is an fan of Fireship)
    - vscode-icons-team.vscode-icons
    # GitLens for seeing file annonations and more
    - eamodio.gitlens
    # Wait a sec, Docker stuff?
    - ms-azuretools.vscode-docker
    # Rust Analyizer is configured in this repo's .vscode/settings.json, so we'll add it also
    - matklad.rust-analyzer
    # Don't forget the main one, but YOLO if you enabled both.
    #- rust-lang.rust
    # Requires the Hadolint binary on PATH or things will go into chaos.
    - exiasr.hadolint

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false

ports:
  # ignore when the Postgres server starts by either our bashrc hack or one of the before scripts.
  - port: 5432
    onOpen: ignore
    visibility: private
