image:
  file: .gitpod.Dockerfile
  context: .devcontainer

# See https://www.gitpod.io/docs/config-start-tasks to configure tasks in Gitpod
# Before and init tasks are better run in tandem during prebuilds, which you can learn more at https://www.gitpod.io/docs/prebuilds.
tasks:
  # Install Yarn dependencies during prebuilds first with IS_GITPOD_PREBUILD set to 1 to ensure we don't hit that "api/.env Not found" error. Possibly implement Docker Compose and installing crates for the cli directory soon
  - init: IS_GITPOD_PREBUILD=1 ./setup.sh

vscode:
  # Open this repo inside Gitpod to upload *.vsix files that's not found on Open VSIX or if you built an opensource VS Code extension yourself.
  # WARNING: DO NOT UPLOAD EVERYTHING from Microsoft VS Code Extensions Store for legal reasons. See VS Code terms of use for details.
  extensions:
    # Prettier VS Code extension
    - esbenp.prettier-vscode
    # VS Code intgration for ShellCheck so see the docs on how to ignore errors, among other things
    - timonwong.shellcheck
    # VS Code icon theme Fireship.io uses (Disclaimer: @ajhalili2006 is an fan of Fireship)
    - vscode-icons-team.vscode-icons
    # GitLens for seeing file annonations and more
    - eamodio.gitlens
    # Wait a sec, Docker stuff?
    - ms-azuretools.vscode-docker
    
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
