services:
  postgresql:
    image: postgres:13
    restart: always
    container_name: hydralite-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hydralite
      POSTGRES_PASSWORD: hydralite
      POSTGRES_DB: hydralite-db
  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
