services:
  postgresql:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379
