version: "3.9" # optional since v1.27.0
services:
  postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
