version: "3.9"
services:
  api:
    build: "../../api"
    networks:
      - api
    depends_on:
      - postgresql
      - redis
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgresql:5432"
      REDIS_HOST: "redis"
  postgresql:
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - api
  redis:
    image: redis
    networks:
      - api
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
networks:
  api:
    driver: bridge
